const TOP_OFFSET = 60
const STREAMING_MOVIES_API_URL =
  process.env.NEXT_PUBLIC_STREAMING_MOVIES_API_URL
const SEARCH_ACTOR_GOOGLE = process.env.NEXT_PUBLIC_SEARCH_ACTOR_GOOGLE
const IMAGE_CACHE_HOST_URL = process.env.NEXT_PUBLIC_IMAGE_CACHE_HOST_URL
const SEARCH_DEBOUNCE = 400

export {
  TOP_OFFSET,
  STREAMING_MOVIES_API_URL,
  SEARCH_ACTOR_GOOGLE,
  SEARCH_DEBOUNCE,
  IMAGE_CACHE_HOST_URL,
}
